name: 'hexo-deploy'
author: 'according-reuixiy'
description: 'Deploy your Hexo site to GitHub Pages, via GitHub Actions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-up-circle'  
  color: 'yellow'